### ISSUE TITLE
Youtube issues

### ISSUE THREAD

**Issue by Onlycplease** [ReVanced/GmsCore#18]
I reinstalled revanced manager and gmscore services. I then choose the suggested version of youtube and patched it. When i try to watch a video, after 30 seconds or so it gets stuck without starting again unless i close and open it again, and after 30 more seconds it gets stuck again. I tried differen versions of youtube too and the problem is the same so i figured it has to do with gmscore services (might be completely off)
Hope you can help me.

**Comment by Corsaka** [comment]
yeah, i'm experiencing same black screen of death issue that was previously solved via client spoofing. no such issues on vanced microG that i was forced to update from due to youtube complaining about app version.

playback very consistently stutters around the 30-40 second mark before the black screen infinite buffering hits. shorts remain entirely unaffected.

**Comment by JermPL** [comment]
Same issue on a freshly downloaded and patched apk with the proper GmsCore.

**Comment by Corsaka** [comment]
restarting the entire phone after clearing cache seems to resolve the issue!

**Comment by fagank-y21** [comment]
> restarting the entire phone after clearing cache of revanced/gmscore seems to resolve the issue!

One other thing to add, force stop the service before clearing the cache. In my experience you need to do that as well otherwise it will still not work.
